### ISSUE TITLE
[Bug] Cannot use "+" symbol

### ISSUE THREAD

**Issue by TheCableGuy99** [leiweibau/Pi.Alert#324] opened 2024-06-22 01:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and the Help/FAQ section of Pi.Alert

### Current Behavior

I'm trying to use the "+" symbol in the "Model" field but when I come back to that device it's been removed.

### Environment

Raspberry Pi 4B running Debian 11

### Anything else?

Can it be made to support special characters in all input fields?

Thanks.

**Comment by leiweibau** [comment] 2024-06-22 06:06
Hello @TheCableGuy99

I can reproduce the error. At first I suspect that the "+" character is removed as part of a filtering of special characters/operators, but I'll take a look at it.

**Comment by leiweibau** [comment] 2024-06-22 20:34
The error actually affects all text fields, if you take it exactly 😉 I have now fixed it for the Model, Owner and Name fields. If it doesn't have any negative effects, I will also test other fields. The release of the update will still take a while because I'm still working on the satellite feature.

**Comment by leiweibau** [comment] 2024-06-29 19:42
Update released with https://github.com/leiweibau/Pi.Alert/commit/6164a07b725c0f36e2165680f9a43d35a4b56052

**Closed by leiweibau** 2024-06-29 19:42 UTC
Labels: Bug, With the next update
