### ISSUE TITLE
Pi.Alert status info faded

### ISSUE THREAD

**Issue by ramess18** [leiweibau/Pi.Alert#60] opened 2023-01-04 17:23 UTC
Hello,
I'd like to ask about status info (left top corner). After update it seems grayed out ...see picture.
![image](https://user-images.githubusercontent.com/16610727/210612832-2d3ec5dc-097b-434f-9ee3-3491753c3d82.png)
Could you please help me to be not grayed out?

**Comment by leiweibau** [comment] 2023-01-04 18:04
I can't reproduce the error on my end. Neither in mobile browsers nor in desktop browsers. Even after clearing the cache, I can't reproduce your error.
<img width="221" alt="Bildschirmfoto 2023-01-04 um 18 59 24" src="https://user-images.githubusercontent.com/105860611/210620250-73b0a2fe-a2b4-4190-a042-60f393b31a48.png">

Have you cleared the cache yourself?

**Comment by ramess18** [comment] 2023-01-04 18:13
Yes, I did cleared cache. Also I tryed in different browsers (Edge, Firefox, Brave). I experienced this behaviour in version 3.7.13 too. I waited for version 3.7.14 but it has the same issue.

**Comment by leiweibau** [comment] 2023-01-04 18:49
I just reapplied the update to my test environment. I opened a browser in private mode and called the frontend, yet I cannot reproduce the error.

Only when I remove `<link rel="stylesheet" href="css/pialert.css">` in the source code of the page, I come close to your error pattern. Can you please check if in the page source (area around line 55) this line exists in the source code? Do you have any extensions active that could interfere with a page layout?

**Comment by leiweibau** [comment] 2023-01-04 19:05
Your right. There was an issue while minifying the CSS files. I will push a new update in the next minutes with the old "big" CSS files.

**Comment by leiweibau** [comment] 2023-01-04 19:35
Should be fixed now with 3.7.15

**Comment by ramess18** [comment] 2023-01-04 20:50
I updated to 3.7.15 - this release fixed it.
Thank you so much for such a quick solution. You are great!

**Closed** 2023-01-04 20:50 UTC
Labels: question
