### ISSUE TITLE
Database locked

### ISSUE THREAD

**Issue by flwilk** [leiweibau/Pi.Alert#82] opened 2023-02-14 06:40 UTC
Database gets locked. Even after reboot I can edit 2 - 3 devices and then it's locked again.

**Comment by flwilk** [comment] 2023-02-14 13:41
Found the solution by my own. I run it on an LXC on root. You have to add root to the group of www-data and it works.

**Comment by leiweibau** [comment] 2023-02-14 14:23
Hello.

Which operating system?
Are you using the latest version?
Have you already read the FAQ?
What is the permission of the database folder and the database itself?
What happens if you pause arp-scan during editing and start it again after editing?
Does the scan also report an error due to a locked database?

I'm really happy to help while I take care of maintaining and developing Pi.Alert, but a little more information than X or Y doesn't work is needed.

**Comment by flwilk** [comment] 2023-02-15 07:49
One step ahead:
I'm running both (pihole + pialert) on an LXC (on Proxmox) with ubuntu 22.04.
I added the root-user to the www-data group and the behavior gets much better. Now I can Edit 10-12 devices until the db gets locked. After 10-15minutes it works again. Doesn't seem to be related to the arp scan.

Perhaps its a combination of my network-setting and the arp scan:

I have serveral vlans on OPNsense running. For every vlan I created a network interface connected to the LXC an the specific vlan. Actually there are 6vlans. I configured the pi.alert config this way:

`SCAN_SUBNETS    = [ '192.168.8.0/24 --interface=eth0', '192.168.10.0/24 --interface=eth1', '192.168.20.0/24 --interface=eth2', '192.168.30.0/24 --interface=eth3', '192.168.40.0/24 --interface=eth4', '192.168.1.0/24 --interface=eth5' ]`

**Comment by flwilk** [comment] 2023-02-15 08:20
`Scanning...
arp-scan Method...
arp-scan: Multiple interfaces
Pi-hole Method...
Traceback (most recent call last):
File "/root/pialert/back/pialert.py", line 2229, in
sys.exit(main())
File "/root/pialert/back/pialert.py", line 109, in main
res = scan_network()
File "/root/pialert/back/pialert.py", line 487, in scan_network
copy_pihole_network()
File "/root/pialert/back/pialert.py", line 654, in copy_pihole_network
sql.execute ("DELETE FROM PiHole_Network")
sqlite3.OperationalError: database is locked`

database locked even in scan-log

**Comment by leiweibau** [comment] 2023-02-15 11:33
Can you find out which process is locking the database?

`fuser ~/pialert/db/pialert.db`

**Comment by flwilk** [comment] 2023-02-15 12:38
1. proved database is already locked
2. `fuser ~/pialert/db/pialert.db`
3. `/root/pialert/db/pialert.db:  6006`
4. top

   PID USER         PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                  
   6190 root            20   0    7372   2676   2100 R   0.3   0.3   0:00.04 top                                                                                      
      1 root               20   0  165780   9488   6676 S   0.0   0.9   0:01.15 systemd                                                                                  
     42 root              20   0   39668  19100  18032 S   0.0   1.8   0:01.02 systemd-journal                                                                          
    103 systemd+    20   0   16248   6836   5800 S   0.0   0.7   0:00.72 systemd-network                                                                          
    105 root             20   0  234312   5280   4532 S   0.0   0.5   0:00.55 accounts-daemon                                                                          
    106 root             20   0    3884   1960   1728 S   0.0   0.2   0:00.09 cron                                                                                     
    107 message+  20   0    8596   3528   2952 S   0.0   0.3   0:00.42 dbus-daemon                                                                              
    113 root             20   0   30116  16164   7536 S   0.0   1.5   0:00.14 networkd-dispat                                                                          
    114 syslog         20   0  152768   3760   3196 S   0.0   0.4   0:00.20 rsyslogd                                                                                 
    115 root             20   0   14900   5380   4572 S   0.0   0.5   0:00.18 systemd-logind                                                                           
    124 systemd+   20   0   25256  10244   6312 S   0.0   1.0   0:00.82 systemd-resolve                                                                          
    150 cloudfl+      20   0  745092  24332  10548 S   0.0   2.3   0:04.77 cloudflared                                                                              
    152 root            20   0  216876  21544  15928 S   0.0   2.1   0:01.20 php-fpm8.1                                                                               
    171 root            20   0   15420   6836   5260 S   0.0   0.7   0:00.00 sshd                                                                                     
    176 root            20   0    2816    948    864 S   0.0   0.1   0:00.00 agetty                                                                                   
    179 root            20   0    7796   3504   2612 S   0.0   0.3   0:00.01 login                                                                                    
    180 root            20   0    2816    920    828 S   0.0   0.1   0:00.00 agetty                                                                                   
    187 www-data  20   0    5148   3164   2532 S   0.0   0.3   0:00.87 lighttpd                                                                                 
    198 www-data  20   0  215672  22096  16540 S   0.0   2.1   0:00.03 php-cgi                                                                                  
    199 www-data  20   0  215672  21924  16368 S   0.0   2.1   0:00.02 php-cgi                                                                                  
    205 pihole        20   0  622264  12912   7064 S   0.0   1.2   1:33.87 pihole-FTL                                                                               
    228 www-data  20   0  215936  13532   7168 S   0.0   1.3   0:00.01 php-cgi                                                                                  
    229 www-data  20   0  215936  11976   5960 S   0.0   1.1   0:00.01 php-cgi                                                                                  
    230 www-data  20   0  215936  12116   6084 S   0.0   1.2   0:00.01 php-cgi                                                                                  
    231 www-data  20   0  215936  12116   6084 S   0.0   1.2   0:00.01 php-cgi                                                                                  
    232 www-data  20   0  216304  15240   8500 S   0.0   1.5   0:00.18 php-cgi                                                                                  
    233 www-data  20   0  216288  15400   8544 S   0.0   1.5   0:00.18 php-cgi                                                                                  
    236 www-data  20   0  291360  20088  11724 S   0.0   1.9   0:00.26 php-cgi                                                                                  
    237 www-data  20   0  216268  16516   8672 S   0.0   1.6   0:00.17 php-cgi                                                                                  
    243 root            20   0    3644   1876   1224 S   0.0   0.2   0:00.40 dhcpcd 

No such PID???

**Comment by flwilk** [comment] 2023-02-15 12:59
Damn! I cut off the screen...again:
root@pihole:~# fuser ~/pialert/db/pialert.db
/root/pialert/db/pialert.db:  6683

   6103 root      20   0    5644   4264   2584 S   0.0   0.4   0:00.02 bash                                                                                     
   6681 root      20   0    7328   3140   2344 S   0.0   0.3   0:00.00 cron                                                                                     
   6682 root      20   0    2888    816    720 S   0.0   0.1   0:00.00 sh                                                                                       
   6683 root      20   0   35064  26020   8324 S   0.0   2.5   0:00.36 python3                                                                                  
   6792 root      20   0    7372   2732   2156 R   0.0   0.3   0:00.07 top                                                                                      
   6793 root      20   0  132316   8540   6728 S   0.0   0.8   0:00.00 dig

**Comment by leiweibau** [comment] 2023-02-15 13:03
At the moment it seems that an already running scan is blocking a current scan. Since this blocking seems to last only a short time, the solution is a bit difficult. You could try to resolve this phenomenon by changing the cronjob from 5min to 10min. Unfortunately I can't reproduce your complex setup.

**Comment by flwilk** [comment] 2023-02-15 13:58
Hey there,
okay I will try and report.

**Comment by jokob-sk** [comment] 2023-02-15 21:30
Not sure if this helps but just FYI: I think what reduced DB locks on my fork is reducing DB opens / closes and replace them with commits if the DB call writes into the DB. It's mostly this and the following commit: https://github.com/jokob-sk/Pi.Alert/commit/b86cbb3a39420301cd903b16d93e6efe34441d4a

**Comment by leiweibau** [comment] 2023-02-15 22:41
In the case of the backend, the number of connections to the database is limited. 1x during scanning. Afterwards, the connection is disconnected in order to open it again for reporting. Here I have removed another connection establishment. Of course, depending on the duration of the scan, the database can be open for a while, which then leads to a lock when another process (editing entries) wants to access it.

On the frontend side, I have not yet looked deeply for optimizations. However, I'll wait for the feedback for now.

**Comment by jokob-sk** [comment] 2023-02-16 00:09
I only open the DB once with the wal SQLlite mode in the back end and I never close it (only on application end). Ive done the same on to front end if I remember correctly. This approach greatly reduced DB locks on my fork as far as I can tell.

**Comment by flwilk** [comment] 2023-02-17 07:41
Unfortunately, this did not work. Database still locks.

**Comment by leiweibau** [comment] 2023-02-17 09:11
I just released a new update with several fixes. Also included is the removal of an unnecessary database connection. You are welcome to test the update. However, I am not confident that this will solve the problem for you, as I cannot currently explain what is causing it.

How long does a single scan take for you?
How many arp-scan processes are active during a scan?

**Comment by flwilk** [comment] 2023-02-20 07:14
Good Morning!
The last change did it! It works! I edited around 25 devices without lock!

- A single scan takes about 2-3 minutes
- There are as many processes as network adapters configured
- There are about 80-90 active devices and about 130 all together

Great work, thank you!

**Comment by leiweibau** [comment] 2023-02-20 07:33
I am happy to read that. Thanks for the feedback.

**Closed** 2023-02-20 08:09 UTC

**Comment by leiweibau** [comment] 2023-02-20 11:38
And of course thanks to @jokob-sk
