### ISSUE TITLE
Help with unknown device

### ISSUE THREAD

**Issue by hspindel** [leiweibau/Pi.Alert#149] opened 2023-08-19 08:54 UTC
I am getting a device detected by pialert at IP fe80::25f:86ff:fe93:a422.  The first three parts of the MAC OUI are 00:5f:86 indicating that this device is a Cisco device.

If I delete the device, it comes back on the next scan.

I have exactly one Cisco device on my network.  I have tried unplugging that device, deleting it in pialert, and it comes right back.  (It's an old Cisco router, and I don't think ti even supports IPv6.)

I have tried disabling IPv6 on the Pi on which pialert is running.  Generally, I have IPv6 disabled everywhere on my local network, but I could have missed some places.

I can't figure out where pialert is discovering this device.  I have no DHCP supporting IPv6 active, so I don't even know how this device could get an IP.  I know very little about IPv6, but I tried to lookup the IP address and it came back as a local address, so I don't think this is an intruder of any sort but actually something that is on my network.

I cannot ping the IPv6 device on the device where pialert is installed.

Any suggestions for tracking down how pialert is detecting this device?

**Comment by leiweibau** [comment] 2023-08-19 09:10
> It's an old Cisco router, and I don't think ti even supports IPv6.

IPv6 is over 20 years old ;)
fe80::25f:86ff:fe93:a422 is a link local address that the device gives itself without the need for additional support for IPv6 in the network. If you have Pi-hole installed, the probability that it comes from there is quite high. Can you get more information from the device details?

**Comment by hspindel** [comment] 2023-08-19 09:38
This Cisco router is more than 20 years old I think.  :-)

The only useful information in the device details is the MAC address, the Vendor, the IPv6 address, and a status of "offline".

I do have pihole installed. ifconfig on the Raspberry Pi where pihole lives doesn't report anything about IPv6.

This isn't something that worries me - I am just trying to understand where that device comes from.

Thank you!

**Comment by leiweibau** [comment] 2023-08-22 20:25
I think I can close this.

**Comment by hspindel** [comment] 2023-08-22 23:24
Ok.  Never did figure out where the IP was coming from...

**Comment by leiweibau** [comment] 2023-08-23 04:16
Have you done this?
> ... also in Pi-hole, look under Tools -> Network to see if you can find the recurring hosts there.

**Comment by hspindel** [comment] 2023-08-23 07:05
Thank you.

pihole does show the device in the network, but also says it never does a DNS query.  Aside from that, all it says is "Cisco Systems" which I already knew.

**Comment by leiweibau** [comment] 2023-08-23 07:13
> pihole does show the device in the network, but also says it never does a DNS query. Aside from that, all it says is "Cisco Systems" which I already knew.

The problem is, the device is in the Pihole database, so Pi.Alert takes it over. You can try to delete it. In the best case it stays gone, then you can also delete it in Pi.Alert. In some cases, it comes again and again (problem of pihole), then it appears also again and again in Pi.Alert. For this reason, there is the Mac Ignore List 😁.

**Comment by hspindel** [comment] 2023-08-23 08:36
I have tried deleting it a couple times from pialert.  It keeps coming back.  I haven't tried telling pihole to delete it - I'll try that now.

Does the MAC ignore list support IPv6?

**Comment by leiweibau** [comment] 2023-08-23 08:42
Since it is a MAC Ignore List, the IP does not matter. If the MAC appears in the results during a scan, it/they will be removed from the results.

**Comment by leiweibau** [comment] 2023-08-26 19:18
Seems to be solved.

**Closed by leiweibau** 2023-08-26 19:18 UTC
